#!/usr/bin/env python3
"""Evaluate reversible K/V, layer, and head lifting over a KV capture matrix."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--matrix-dir", required=True)
    parser.add_argument(
        "--binary",
        default="target/release/examples/cross_stream_lifting_experiment",
    )
    parser.add_argument(
        "--output",
        default="docs/CROSS_STREAM_LIFTING_MATRIX.md",
    )
    args = parser.parse_args()

    matrix_dir = Path(args.matrix_dir)
    binary = Path(args.binary).resolve()
    if not binary.exists():
        subprocess.run(
            ["cargo", "build", "--release", "--example", "cross_stream_lifting_experiment"],
            check=True,
        )

    rows: list[str] = []
    for case_dir in sorted(path for path in matrix_dir.iterdir() if path.is_dir()):
        manifest = json.loads((case_dir / "raw" / "manifest.json").read_text())
        tensor = manifest["tensors"][0]
        active_rows = int(tensor["active_cells"])
        stride = int(tensor["embedding"])
        dtype = str(tensor["dtype"]).removesuffix("le")
        packed = case_dir / "packed"
        command = [
            str(binary),
            "--rows",
            str(active_rows),
            "--stride",
            str(stride),
            "--dtype",
            dtype,
            "--label",
            case_dir.name,
            "--k",
            str(packed / f"cache_k_packed.{dtype}le"),
            "--v",
            str(packed / f"cache_v_packed.{dtype}le"),
        ]
        run = subprocess.run(command, text=True, capture_output=True, check=True)
        rows.extend(
            line
            for line in run.stdout.splitlines()
            if line.startswith("| ")
            and not line.startswith("| dataset")
            and not line.startswith("| ---")
        )

    report = render_report(rows)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report)
    print(report)
    return 0


def render_report(rows: list[str]) -> str:
    parsed = []
    for row in rows:
        cells = [cell.strip() for cell in row.strip("|").split("|")]
        parsed.append((cells, float(cells[5].rstrip("%"))))
    lifting = [(cells, change) for cells, change in parsed if cells[1] != "identity-control"]
    wins = [(cells, change) for cells, change in lifting if change < 0]
    best = min(lifting, key=lambda item: item[1])

    out = "# Reversible Cross-Stream Lifting Matrix\n\n"
    out += "Generated by `scripts/cross_stream_lifting_matrix.py` from direct patched-llama.cpp KV captures.\n\n"
    out += f"- complete rows evaluated: `{len(rows)}`\n"
    out += f"- actual lifting candidates evaluated: `{len(lifting)}`\n"
    out += f"- lifting candidates smaller than production qatq-exact: `{len(wins)}`\n"
    out += f"- best lifting candidate: `{best[0][0]} / {best[0][1]}` at `{best[1]:+.2f}%`\n"
    out += "- comparison includes 32 bytes of experimental framing\n\n"
    out += "| dataset | transform | raw | qatq-exact | candidate | size change | exact | encode change | decode change |\n"
    out += "| --- | --- | ---: | ---: | ---: | ---: | --- | ---: | ---: |\n"
    out += "\n".join(rows)
    out += "\n\n## Claim boundary\n\n"
    out += "- Models: Qwen2.5-0.5B and Phi-4 Mini.\n"
    out += "- Prompts: daily-driver, software-engineering, and long-context.\n"
    out += "- Dtypes: native f16 and bf16.\n"
    out += "- Transforms: K/V XOR and subtraction, adjacent-layer XOR and subtraction, 64/128-wide head XOR, and bounded compositions.\n"
    out += "- Every complete candidate is decoded and compared byte-for-byte before reporting.\n"
    out += "\n## Decision\n\n"
    if wins:
        out += "The experiment found lifting wins, but production promotion still requires a conservative sampled gate and consistent cross-model selection.\n"
    else:
        out += "Do not promote cross-stream lifting. No actual lifting candidate beats production qatq-exact; the two sub-0.02% identity-control ties are not lifting gains. A sample gate cannot create a useful selection opportunity.\n"
    return out


if __name__ == "__main__":
    raise SystemExit(main())
