#!/usr/bin/env python3
"""Evaluate ordered-ULP delta coding over exported llama.cpp KV cases."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--matrix-dir", required=True)
    parser.add_argument(
        "--binary",
        default="target/release/examples/ordered_ulp_delta_experiment",
    )
    parser.add_argument(
        "--output",
        default="docs/ORDERED_ULP_DELTA_MATRIX.md",
    )
    args = parser.parse_args()

    matrix_dir = Path(args.matrix_dir)
    binary = Path(args.binary).resolve()
    if not binary.exists():
        subprocess.run(
            ["cargo", "build", "--release", "--example", "ordered_ulp_delta_experiment"],
            check=True,
        )

    rows: list[str] = []
    for case_dir in sorted(path for path in matrix_dir.iterdir() if path.is_dir()):
        manifest = json.loads((case_dir / "raw" / "manifest.json").read_text())
        tensor = manifest["tensors"][0]
        active_rows = int(tensor["active_cells"])
        stride = int(tensor["embedding"])
        dtype = str(tensor["dtype"]).removesuffix("le")
        packed = case_dir / "packed"
        k_path = packed / f"cache_k_packed.{dtype}le"
        v_path = packed / f"cache_v_packed.{dtype}le"
        command = [
            str(binary),
            "--rows",
            str(active_rows),
            "--stride",
            str(stride),
            "--dtype",
            dtype,
            "--input",
            f"{case_dir.name}-k:{k_path}",
            "--input",
            f"{case_dir.name}-v:{v_path}",
        ]
        run = subprocess.run(command, text=True, capture_output=True, check=True)
        rows.extend(
            line
            for line in run.stdout.splitlines()
            if line.startswith("| ") and not line.startswith("| dataset") and not line.startswith("| ---")
        )

    report = render_report(rows)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report)
    print(report)
    return 0


def render_report(rows: list[str]) -> str:
    selected = []
    rejected = []
    for row in rows:
        cells = [cell.strip() for cell in row.strip("|").split("|")]
        if cells[1] != "strided":
            continue
        change = float(cells[5].rstrip("%"))
        (selected if change < 0 else rejected).append((cells, change))

    selected_bytes_saved = sum(
        int(cells[3]) - int(cells[4]) for cells, _ in selected
    )
    out = "# Ordered-ULP Delta Multi-Model Matrix\n\n"
    out += "Generated by `scripts/ordered_ulp_delta_matrix.py` from direct patched-llama.cpp KV captures.\n\n"
    out += f"- evaluated rows: `{len(rows)}` (three predictors per K/V dataset)\n"
    out += f"- selected first-order strided rows: `{len(selected)}`\n"
    out += f"- rejected first-order strided rows: `{len(rejected)}`\n"
    out += f"- selected bytes saved against production qatq-exact: `{selected_bytes_saved}`\n"
    out += "- selection basis: complete encoded size; no sample gate is claimed\n\n"
    out += "| dataset | predictor | raw | qatq-exact | ULP candidate | size change | exact | encode change | decode change |\n"
    out += "| --- | --- | ---: | ---: | ---: | ---: | --- | ---: | ---: |\n"
    out += "\n".join(rows)
    out += "\n\n## Claim boundary\n\n"
    out += "- Models: Qwen2.5-0.5B and Phi-4 Mini.\n"
    out += "- Prompts: daily-driver, software-engineering, and long-context.\n"
    out += "- Dtypes: native f16 and bf16.\n"
    out += "- Every candidate is decoded and compared byte-for-byte before reporting.\n"
    out += "- A production sample gate is not yet implemented; this matrix measures the full candidate and final size decision.\n"
    out += "\n## Decision\n\n"
    out += "Do not promote ordered-ULP delta to production. The first-order strided candidate wins only two of 24 K/V datasets, both short-prompt Qwen f16 K captures, saving 2,160 bytes in total. It loses on every Phi, bf16, V, and long-prompt Qwen dataset. This selection frequency is too narrow to justify a new wire strategy or even a production sample probe.\n"
    return out


if __name__ == "__main__":
    raise SystemExit(main())
