#!/usr/bin/env python3
"""Evaluate exact 4+1 shared-exponent factoring over a KV capture matrix."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--matrix-dir", required=True)
    parser.add_argument(
        "--binary",
        default="target/release/examples/shared_exponent_4plus1_experiment",
    )
    parser.add_argument(
        "--output",
        default="docs/SHARED_EXPONENT_4PLUS1_MATRIX.md",
    )
    args = parser.parse_args()

    matrix_dir = Path(args.matrix_dir)
    binary = Path(args.binary).resolve()
    if not binary.exists():
        subprocess.run(
            ["cargo", "build", "--release", "--example", "shared_exponent_4plus1_experiment"],
            check=True,
        )

    rows: list[str] = []
    for case_dir in sorted(path for path in matrix_dir.iterdir() if path.is_dir()):
        manifest = json.loads((case_dir / "raw" / "manifest.json").read_text())
        tensor = manifest["tensors"][0]
        stride = int(tensor["embedding"])
        dtype = str(tensor["dtype"]).removesuffix("le")
        input_path = case_dir / "packed" / f"cache_all_packed.{dtype}le"
        command = [
            str(binary),
            "--label",
            case_dir.name,
            "--input",
            str(input_path),
            "--dtype",
            dtype,
            "--stride",
            str(stride),
        ]
        run = subprocess.run(command, text=True, capture_output=True, check=True)
        rows.extend(
            line
            for line in run.stdout.splitlines()
            if line.startswith("| ")
            and not line.startswith("| dataset")
            and not line.startswith("| ---")
        )

    report = render_report(rows)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report)
    print(report)
    return 0


def render_report(rows: list[str]) -> str:
    parsed = []
    for row in rows:
        cells = [cell.strip() for cell in row.strip("|").split("|")]
        parsed.append((cells, float(cells[5].rstrip("%"))))
    shared = [
        (cells, change)
        for cells, change in parsed
        if cells[1] != "field-split-control"
    ]
    wins = [(cells, change) for cells, change in shared if change < 0]
    best = min(shared, key=lambda item: item[1])

    out = "# Exact 4+1 Shared-Exponent Matrix\n\n"
    out += "Generated by `scripts/shared_exponent_4plus1_matrix.py` from direct patched-llama.cpp KV captures.\n\n"
    out += f"- complete rows evaluated: `{len(rows)}`\n"
    out += f"- shared-exponent candidates evaluated: `{len(shared)}`\n"
    out += f"- shared-exponent candidates smaller than production qatq-exact: `{len(wins)}`\n"
    out += f"- best shared-exponent candidate: `{best[0][0]} / {best[0][1]}` at `{best[1]:+.2f}%`\n"
    out += "- comparison includes 32 bytes of experimental framing\n\n"
    out += "| dataset | representation | raw | qatq-exact | candidate | size change | exact | encode change | decode change |\n"
    out += "| --- | --- | ---: | ---: | ---: | ---: | --- | ---: | ---: |\n"
    out += "\n".join(rows)
    out += "\n\n## Claim boundary\n\n"
    out += "- Models: Qwen2.5-0.5B and Phi-4 Mini.\n"
    out += "- Prompts: daily-driver, software-engineering, and long-context.\n"
    out += "- Dtypes: native f16 and bf16.\n"
    out += "- Every representation is decoded and compared byte-for-byte before reporting.\n"
    out += "- Field-split control, fixed-lane exponent reference, and mode-selected exponent reference include all selector, match-mask, exception, and framing costs.\n"
    out += "\n## Decision\n\n"
    if wins:
        out += "The matrix found shared-exponent wins; production consideration still requires a sampled gate and a faster bit-packing implementation.\n"
    else:
        out += "Do not promote 4+1 shared-exponent factoring. No complete shared-exponent representation beats production qatq-exact, so a sample gate cannot create a useful selection opportunity.\n"
    return out


if __name__ == "__main__":
    raise SystemExit(main())
